# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('regiao', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo_contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contato.TipoContato', verbose_name='Tipo de Contato'),
        ),
    ]
