# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.BigIntegerField(),
        ),
    ]
