# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descição')),
                ('ativa', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateTimeField(verbose_name='Data de abertura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor total dos produtos')),
                ('estado', models.CharField(choices=[('SEM_ESTADO', 'Sem estado'), ('SOLICITADO', 'Pedido solicitado'), ('NEGOCIACAO', 'Pedido em negociação'), ('ACEITO', 'Pedido aceito'), ('ENVIADO', 'Pedido enviado')], default='SEM_ESTADO', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço unitário')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Processo')),
                ('limite_produtos', models.IntegerField(verbose_name='Limite de produtos para venda')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=2500, verbose_name='Descição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.Linha')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Processo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
