# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor total dos produtos'),
        ),
    ]
