# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20170112_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('SEM_ESTADO', 'Sem estado'), ('SOLICITADO', 'Pedido solicitado'), ('RECUSADO', 'Pedido em recusado'), ('ACEITO', 'Pedido aceito'), ('ENVIADO', 'Pedido enviado')], default='SEM_ESTADO', max_length=25),
        ),
    ]
