# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import manuais.models


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0003_auto_20160308_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='arquivo',
            field=models.FileField(upload_to=manuais.models.Manual.get_upload_path),
        ),
        migrations.AlterField(
            model_name='manual',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tipomanual',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
