# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0006_contato'),
    ]

#    operations = [
#        migrations.RemoveField(
#            model_name='contato',
#            name='arquivo',
#        ),
#    ]
