# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0007_remove_contato_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='descricao',
        ),
    ]
