# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0008_remove_contato_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cargo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='departamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='regiao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='vendedor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
