# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0009_auto_20160324_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='vendedor',
            field=models.BooleanField(verbose_name='Vendedor/Representante'),
        ),
    ]
