# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0010_auto_20160328_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
