# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0011_delete_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomanual',
            name='material_gestao_e_pessoas',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
