# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0012_tipomanual_material_gestao_e_pessoas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipomanual',
            old_name='material_gestao_e_pessoas',
            new_name='material_gente_e_gestao',
        ),
    ]
