# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=750, verbose_name='Faça uma descrição do chamado')),
                ('resolvido', models.BooleanField()),
                ('data_criacao', models.DateTimeField(verbose_name='Data da criação')),
                ('data_prevista_conclusao', models.DateTimeField(null=True, verbose_name='Data prevista de conclusão')),
                ('data_conclusao', models.DateTimeField(null=True, verbose_name='Data da conclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=700)),
                ('data_interacao', models.DateTimeField(verbose_name='Data da interacao')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dphelp.Chamado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='TipoChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('usuario_executante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_chamado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário atendente')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dphelp.TipoChamado', verbose_name='Tipo de chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário solicitante'),
        ),
    ]
