# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='data_interacao',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 16, 38, 46, 769424), verbose_name='Data'),
            preserve_default=False,
        ),
    ]
