# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20170628_2330'),
        ('chamado', '0003_auto_20160512_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoNConformidade',
            fields=[
                ('chamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chamado.Chamado')),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=750, verbose_name='Faça uma descrição do chamado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto')),
            ],
            bases=('chamado.chamado',),
        ),
        migrations.CreateModel(
            name='InteracaoNCorformidade',
            fields=[
                ('interacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chamado.Interacao')),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_interacao_ti_chamado', to='chamado.ChamadoNConformidade')),
            ],
            bases=('chamado.interacao',),
        ),
        migrations.CreateModel(
            name='TipoChamadoNConformidade',
            fields=[
                ('tipochamado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chamado.TipoChamado')),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('criticidade', models.CharField(max_length=50)),
            ],
            bases=('chamado.tipochamado',),
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.TipoChamadoNConformidade', verbose_name='tipo'),
        ),
    ]
