# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0005_auto_20170629_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
