# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20170628_2330'),
        ('chamado', '0006_auto_20170629_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='lote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='loja.Linha', verbose_name='lote'),
            preserve_default=False,
        ),
    ]
