# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0007_chamadonconformidade_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='document',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
