# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0008_auto_20170630_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamadonconformidade',
            old_name='document',
            new_name='arquivo',
        ),
    ]
