# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamado', '0009_auto_20170630_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tempo_de_fase', models.DateTimeField(verbose_name='Data de Início')),
                ('usuario_executante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_fase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='status',
            field=models.CharField(default='Inicial', max_length=100),
        ),
    ]
