# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0010_auto_20170702_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='fase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chamado_fase_Atual', to='chamado.Fase'),
        ),
    ]
