# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0011_chamadonconformidade_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='usuario_executante',
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='fase',
            field=models.CharField(choices=[('INICIAL', 'INICIAL'), ('INTERMEDIARIO', 'INTERMEDIARIO'), ('FINAL', 'FINAL')], default='INICIAL', max_length=50),
        ),
        migrations.DeleteModel(
            name='Fase',
        ),
    ]
