# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0013_interacaoncorformidade_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacao',
            name='descricao',
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='descricao_causa_raiz',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='descricao_tratamento_definitivo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='descricao_tratamento_preliminar',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='fase',
            field=models.CharField(choices=[('Análise de Causa-Raiz', 'Análise de Causa-Raiz'), ('Tratamento Preliminar', 'Tratamento Preliminar'), ('Tratamento Definitivo', 'Tratamento Definitivo')], default='Análise de Causa-Raiz', max_length=50),
        ),
    ]
