# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0014_auto_20170704_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='fase',
            field=models.CharField(choices=[('Análise de Causa-Raiz', 'Análise de Causa-Raiz'), ('Tratamento Preliminar', 'Tratamento Preliminar'), ('Tratamento Definitivo', 'Tratamento Definitivo')], default='Análise de Causa-Raiz', max_length=50),
        ),
    ]
