# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0017_tipochamadonconformidade_tempo_de_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tempo_sobrando',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 8, 29, 39, 580606, tzinfo=utc), verbose_name='Tempo sobrando'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 8, 5, 29, 31, 741496), '1 Dia'), (datetime.datetime(2017, 7, 10, 5, 29, 31, 741496), '3 Dias'), (datetime.datetime(2017, 7, 12, 5, 29, 31, 741496), '5 Dias')]),
        ),
    ]
