# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0019_auto_20170707_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamadonconformidade',
            old_name='tempo_sobrando',
            new_name='tempo_final',
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 8, 5, 59, 38, 947637), '1 Dia'), (datetime.datetime(2017, 7, 10, 5, 59, 38, 947637), '3 Dias'), (datetime.datetime(2017, 7, 12, 5, 59, 38, 947637), '5 Dias')]),
        ),
    ]
