# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0020_auto_20170707_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 9, 0, 14, 33, 91875), '1 Dia'), (datetime.datetime(2017, 7, 11, 0, 14, 33, 91875), '3 Dias'), (datetime.datetime(2017, 7, 13, 0, 14, 33, 91875), '5 Dias')]),
        ),
    ]
