# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 00:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0023_auto_20170712_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 12, 22, 53, 36, 171936), '1 Dia'), (datetime.datetime(2017, 7, 15, 21, 53, 36, 171936), '3 Dias'), (datetime.datetime(2017, 7, 17, 21, 53, 36, 171936), '5 Dias')]),
        ),
    ]
