# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0024_auto_20170712_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 14, 2, 26, 36, 292145), '1 Dia'), (datetime.datetime(2017, 7, 16, 2, 26, 36, 292145), '3 Dias'), (datetime.datetime(2017, 7, 18, 2, 26, 36, 292145), '5 Dias')]),
        ),
    ]
