# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0025_auto_20170713_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='fase',
            field=models.CharField(choices=[('Análise de Causa-Raiz', 'Análise de Causa-Raiz'), ('Tratamento Preliminar', 'Tratamento Preliminar'), ('Tratamento Definitivo', 'Tratamento Definitivo'), ('Análise de Procedência', 'Análise De Procedência'), ('Validação do Gestor', 'Validação do Gestor')], default='Análise de Causa-Raiz', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 16, 11, 33, 54, 951254), '1 Dia'), (datetime.datetime(2017, 7, 15, 15, 33, 54, 951254), '3 Dias'), (datetime.datetime(2017, 7, 14, 19, 33, 54, 951254), '5 Dias')]),
        ),
    ]
