# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0026_auto_20170713_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 16, 11, 45, 43, 947717), '1 Dia'), (datetime.datetime(2017, 7, 15, 15, 45, 43, 947717), '3 Dias'), (datetime.datetime(2017, 7, 14, 19, 45, 43, 947717), '5 Dias')]),
        ),
    ]
