# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0027_auto_20170713_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='analise_procedencia_atrasou',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='analise_causa_raiz_atrasou',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='tratamento_definitivo_atrasou',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='tratamento_preliminar_atrasou',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='validacao_gestor_atrasou',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 17, 0, 51, 58, 911765), '1 Dia'), (datetime.datetime(2017, 7, 16, 4, 51, 58, 911765), '3 Dias'), (datetime.datetime(2017, 7, 15, 8, 51, 58, 911765), '5 Dias')]),
        ),
    ]
