# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0028_auto_20170713_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaoncorformidade',
            name='validacao_gestor_atrasou',
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='fase',
            field=models.CharField(choices=[('Análise de Causa-Raiz', 'Análise de Causa-Raiz'), ('Tratamento Preliminar', 'Tratamento Preliminar'), ('Tratamento Definitivo', 'Tratamento Definitivo'), ('Análise de Procedência', 'Análise De Procedência'), ('Validação do Gestor', 'Validação do Gestor')], default='Análise de Procedência', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 17, 2, 53, 23, 462047), '1 Dia'), (datetime.datetime(2017, 7, 16, 6, 53, 23, 462047), '3 Dias'), (datetime.datetime(2017, 7, 15, 10, 53, 23, 462047), '5 Dias')]),
        ),
    ]
