# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0029_auto_20170713_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='analise_causa_raiz_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tratamento_definitivo_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tratamento_preliminar_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 17, 3, 13, 17, 935306), '1 Dia'), (datetime.datetime(2017, 7, 16, 7, 13, 17, 935306), '3 Dias'), (datetime.datetime(2017, 7, 15, 11, 13, 17, 935306), '5 Dias')]),
        ),
    ]
