# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0030_auto_20170713_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 18, 13, 37, 20, 144729), '1 Dia'), (datetime.datetime(2017, 7, 17, 17, 37, 20, 144729), '3 Dias'), (datetime.datetime(2017, 7, 16, 21, 37, 20, 144729), '5 Dias')]),
        ),
    ]
