# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0031_auto_20170715_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tempo_analise_procecencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='tempo_analise_causa_raiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='tempo_tratamento_definitivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interacaoncorformidade',
            name='tempo_tratamento_preliminar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 19, 11, 5, 58, 344353), '1 Dia'), (datetime.datetime(2017, 7, 18, 15, 5, 58, 344353), '3 Dias'), (datetime.datetime(2017, 7, 17, 19, 5, 58, 344353), '5 Dias')]),
        ),
    ]
