# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0032_auto_20170716_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='analise_causa_raiz_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tempo_analise_causa_raiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tempo_tratamento_definitivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tempo_tratamento_preliminar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tratamento_definitivo_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamadonconformidade',
            name='tratamento_preliminar_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 19, 12, 55, 26, 307640), '1 Dia'), (datetime.datetime(2017, 7, 18, 16, 55, 26, 307640), '3 Dias'), (datetime.datetime(2017, 7, 17, 20, 55, 26, 307640), '5 Dias')]),
        ),
    ]
