# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0035_auto_20170716_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_analise_causa_raiz',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 115614), null=True),
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_analise_procecencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 115494), null=True),
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_tratamento_definitivo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 115555), null=True),
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_tratamento_preliminar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 115669), null=True),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tempo_analise_causa_raiz',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 122238), null=True),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tempo_tratamento_definitivo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 122181), null=True),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tempo_tratamento_preliminar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 6, 56, 32, 122301), null=True),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 19, 14, 56, 32, 112867), '1 Dia'), (datetime.datetime(2017, 7, 18, 18, 56, 32, 112867), '3 Dias'), (datetime.datetime(2017, 7, 17, 22, 56, 32, 112867), '5 Dias')]),
        ),
    ]
