# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0037_auto_20170716_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_analise_causa_raiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_analise_procecencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_tratamento_definitivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadonconformidade',
            name='tempo_tratamento_preliminar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tempo_analise_causa_raiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tempo_tratamento_definitivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interacaoncorformidade',
            name='tempo_tratamento_preliminar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 19, 15, 2, 4, 593787), '1 Dia'), (datetime.datetime(2017, 7, 18, 19, 2, 4, 593787), '3 Dias'), (datetime.datetime(2017, 7, 17, 23, 2, 4, 593787), '5 Dias')]),
        ),
    ]
