# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0038_auto_20170716_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 19, 15, 2, 52, 698059), '1 Dia'), (datetime.datetime(2017, 7, 18, 19, 2, 52, 698059), '3 Dias'), (datetime.datetime(2017, 7, 17, 23, 2, 52, 698059), '5 Dias')]),
        ),
    ]
