# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0040_auto_20170716_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadonconformidade',
            name='chamado_atrasou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipochamadonconformidade',
            name='tempo_de_duracao',
            field=models.DateTimeField(choices=[(datetime.datetime(2017, 7, 20, 11, 10, 48, 663918), '1 Dia'), (datetime.datetime(2017, 7, 19, 15, 10, 48, 663918), '3 Dias'), (datetime.datetime(2017, 7, 18, 19, 10, 48, 663918), '5 Dias')]),
        ),
    ]
