# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tihelp', '0012_remove_chamado_ativar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoanonimo',
            name='descricao',
            field=models.CharField(max_length=1500, verbose_name='Faça uma descrição do chamado'),
        ),
    ]
