# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tihelp', '0013_auto_20160406_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_ti', to=settings.AUTH_USER_MODEL, verbose_name='Usuário solicitante'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacao_ti', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
